version: '3.8'

services:
  servidor:
    build:
      context: .
      dockerfile: ./servidor/Dockerfile
    ports:
      - "65432:65432"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535

  cliente:
    build:
      context: .
      dockerfile: ./cliente/Dockerfile
    depends_on:
      - servidor

  cliente-estresse:
    build:
      context: .
      dockerfile: ./cliente_estresse/Dockerfile
    depends_on:
      - servidor
    # Este serviço não inicia por padrão. Use 'docker-compose run' para executá-lo.
    # Exemplo: docker-compose run cliente-estresse 100
    entrypoint: ["/main"]